Description: EC2 instance for code-server

Parameters:
  InstanceName:
    Type: String
    Description: Code-server EC2 instance name
    Default: CodeServer
  InstanceVolumeSize:
    Type: Number
    Description: Code-server EC2 instance volume size in GB
    Default: 200
  InstanceType:
    Description: Code-server EC2 instance type
    Type: String
    Default: trn1.2xlarge
  InstanceOperatingSystem:
    Description: Code-server EC2 operating system
    Type: String
    Default: Ubuntu-22
    AllowedValues: ['Ubuntu-22', 'Ubuntu-24']
  CodeServerUser:
    Type: String
    Description: UserName for code-server
    Default: coder
  HomeFolder:
    Type: String
    Description: Folder to open in code-server
    Default: /work

Conditions:
  IsGraviton:
    !Not [
      !Equals [
        !Select [0, !Split ['g', !Select [0, !Split ['.', !Ref InstanceType]]]],
        !Select [0, !Split ['.', !Ref InstanceType]],
      ],
    ]
  IsTRN1:
    !Or [
      !Equals [!Select [0, !Split ['.', !Ref InstanceType]], 'trn1'],
      !Equals [!Select [0, !Split ['.', !Ref InstanceType]], 'trn1n'],
      !Equals [!Select [0, !Split ['.', !Ref InstanceType]], 'trn2'],
      !Equals [!Select [0, !Split ['.', !Ref InstanceType]], 'trn2u']
    ]

Mappings:
  ArmImage:
    # aws ssm get-parameters-by-path --path "/aws/service/canonical/ubuntu/" --recursive --query "Parameters[*].Name"  > canonical-ami.txt
    # aws ssm get-parameters-by-path --path "/aws/service/ami-amazon-linux-latest/" --recursive --query "Parameters[*].Name"  > amazon-ami.txt
    Ubuntu-22:
      ImageId: '{{resolve:ssm:/aws/service/canonical/ubuntu/server/jammy/stable/current/arm64/hvm/ebs-gp2/ami-id}}'
    Ubuntu-24:
      ImageId: '{{resolve:ssm:/aws/service/canonical/ubuntu/server/noble/stable/current/arm64/hvm/ebs-gp3/ami-id}}'
  AmdImage:
    Ubuntu-22:
      ImageId: '{{resolve:ssm:/aws/service/canonical/ubuntu/server/jammy/stable/current/amd64/hvm/ebs-gp2/ami-id}}'
    Ubuntu-24:
      ImageId: '{{resolve:ssm:/aws/service/canonical/ubuntu/server/noble/stable/current/amd64/hvm/ebs-gp3/ami-id}}'
  # Deep Learning AMI with Neuron for TRN1 instances
  NeuronImage:
    Ubuntu-22:
      ImageId: '{{resolve:ssm:/aws/service/neuron/dlami/multi-framework/ubuntu-22.04/latest/image_id}}'
    Ubuntu-24:
      ImageId: '{{resolve:ssm:/aws/service/neuron/dlami/multi-framework/ubuntu-22.04/latest/image_id}}'
  AWSRegionsPrefixListID:
    # aws ec2 describe-managed-prefix-lists  --region <REGION> | jq -r '.PrefixLists[] | select (.PrefixListName == "com.amazonaws.global.cloudfront.origin-facing") | .PrefixListId'
    ap-northeast-1:
      PrefixList: pl-58a04531
    ap-northeast-2:
      PrefixList: pl-22a6434b
    ap-south-1:
      PrefixList: pl-9aa247f3
    ap-southeast-1:
      PrefixList: pl-31a34658
    ap-southeast-2:
      PrefixList: pl-b8a742d1
    ca-central-1:
      PrefixList: pl-38a64351
    eu-central-1:
      PrefixList: pl-a3a144ca
    eu-north-1:
      PrefixList: pl-fab65393
    eu-west-1:
      PrefixList: pl-4fa04526
    eu-west-2:
      PrefixList: pl-93a247fa
    eu-west-3:
      PrefixList: pl-75b1541c
    sa-east-1:
      PrefixList: pl-5da64334
    us-east-1:
      PrefixList: pl-3b927c52
    us-east-2:
      PrefixList: pl-b6a144df
    us-west-1:
      PrefixList: pl-4ea04527
    us-west-2:
      PrefixList: pl-82a045eb

Resources:
  CDKToolkitPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CDKToolkitPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:CreateChangeSet
              - cloudformation:DescribeStacks
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:DeleteChangeSet
            Resource: !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/CDKToolkit/*'
      Roles:
        - !Ref CodeServerInstanceBootstrapRole

  CodeServerInstanceBootstrapRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub ec2.${AWS::URLSuffix}
                - !Sub ssm.${AWS::URLSuffix}
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess # scope this down later
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Sub arn:${AWS::Partition}:iam::aws:policy/CloudWatchAgentServerPolicy
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonQDeveloperAccess

  CodeServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref CodeServerInstanceBootstrapRole

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F1000
            reason: All outbound traffic should be allowed from this instance. The EC2 instance is provisioned in the default VPC, which already has this egress rule, and it is not possible to duplicate this egress rule in the default VPC
    Properties:
      GroupDescription: Security Group for code-server - only allow CloudFront ingress
      SecurityGroupIngress:
        - Description: Allow HTTP from com.amazonaws.global.cloudfront.origin-facing
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourcePrefixListId:
            !FindInMap [AWSRegionsPrefixListID, !Ref 'AWS::Region', PrefixList]

  CodeServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !If
        - IsTRN1
        - !FindInMap [NeuronImage, !Ref InstanceOperatingSystem, ImageId]
        - !If
          - IsGraviton
          - !FindInMap [ArmImage, !Ref InstanceOperatingSystem, ImageId]
          - !FindInMap [AmdImage, !Ref InstanceOperatingSystem, ImageId]
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref InstanceVolumeSize
            VolumeType: gp3
            DeleteOnTermination: true
            Encrypted: true
      Monitoring: true
      SecurityGroupIds:
        - !Ref SecurityGroup
      IamInstanceProfile: !Ref CodeServerInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #cloud-config
          hostname: ${InstanceName}
          runcmd:
            - mkdir -p ${HomeFolder} && chown -R ${CodeServerUser}:${CodeServerUser} ${HomeFolder}
      Tags:
        - Key: Name
          Value: !Ref InstanceName

Outputs:
  CodeServerInstanceId:
    Description: EC2 instance ID
    Value: !Ref CodeServerInstance
  CodeServerInstancePublicDnsName:
    Description: EC2 instance public DNS name
    Value: !GetAtt CodeServerInstance.PublicDnsName
